name: Push commit
on: push
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_TOKEN }}
      - name: Create report file
        run: date > report.txt
      - name: Commit report
        run: |
          git config --global user.name 'andrewbcooper'
          git config --global user.email 'andrew.cooper@seattlechildrens.org'
          git add report.txt
          git commit -am "Automated report"
          git push
